<?php

/**
 * @file
 * Contains skeleton_module.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function skeleton_module_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the skeleton_module module.
    case 'help.page.skeleton_module':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Skeleton module') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function skeleton_module_theme() {
  return [
    'skeleton_module' => [
      'render element' => 'children',
    ],
  ];
}

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_alter().
 */
function skeleton_module_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  // Change form id here.
  if ($form_id == 'form_test_alter_form') {
    \Drupal::messenger()->addMessage('form_test_form_alter() executed.');

    $form['submit_alter'] = [
      '#type' => 'button',
      '#title' => t('Submit alter'),
      '#description' => t('Submit alter button'),
      '#default_value' => 'Submit alter',
      '#weight' => '0',
    ];

  }
}

/**
 * Implements hook_theme().
 */
function skeleton_module_theme() {
  return [
    'default_plugin_block' => [
      'variables' => [
        'content' => NULL
      ],
      'render element' => 'children',
    ],
  ];
}

use Drupal\Core\Entity\EntityTypeInterface;

/**
 * Implements hook_entity_bundle_field_info_alter().
 */
function skeleton_module_entity_bundle_field_info_alter(&$fields, EntityTypeInterface $entity_type, $bundle) {
  if ($bundle === 'article') {
    if (isset($fields['body'])) {
      // Use the ID as defined in the annotation of the constraint definition.
      $fields['body']->addConstraint('example_constraint', []);
    }
  }
}