name: dcg_module_configuration_entity
type: module
description: 'Provides a dcg_module_configuration_entity configuration entity.'
package: Custom
core: 8.x
core_version_requirement: ^8 || ^9
configure: entity.dcg_module_configuration_entity.collection
