<?php

/**
 * @file
 * Provides a dcg_module_content_entity entity type.
 */

use Drupal\Core\Render\Element;

/**
 * Implements hook_theme().
 */
function dcg_module_content_entity_theme() {
  return [
    'dcg_module_content_entity' => [
      'render element' => 'elements',
    ],
  ];
}

/**
 * Prepares variables for dcg_module_content_entity templates.
 *
 * Default template: dcg-module-content-entity.html.twig.
 *
 * @param array $variables
 *   An associative array containing:
 *   - elements: An associative array containing the dcg_module_content_entity information and any
 *     fields attached to the entity.
 *   - attributes: HTML attributes for the containing element.
 */
function template_preprocess_dcg_module_content_entity(array &$variables) {
  foreach (Element::children($variables['elements']) as $key) {
    $variables['content'][$key] = $variables['elements'][$key];
  }
}
